linuxmint/xapp

libxapp/xapp-display.c

This was deprecated with the invention of gtk3.0. Instead switch to the modern
method of using css style providers and classes. This quiets some build warnings
we get.

xapp-display: Don't use deprecated gtk_widget_modify_bg

---

autogen.sh

***Warning*** USE_COMMON_DOC_BUILD is deprecated, you may remove it from autogen.sh
***Warning*** USE_GNOME2_MACROS is deprecated, you may remove it from autogen.sh
***Warning*** PKG_NAME is deprecated, you may remove it from autogen.sh

Fix Warnings

---

debian/control
debian/rules

Taken from https://anonscm.debian.org/git/pkg-cinnamon/xapp.git/commit/?id=e121aaa12eb469206f452755992d6ee211d46425

Use python3 as all scripts are in python3

---

docs/reference/xapp-docs.xml
libxapp/Makefile.am
libxapp/xapp-preferences-window.c
libxapp/xapp-preferences-window.h

This gives us a basic reusable dialog window we can use in our apps. It
supplies a simple setup with a GtkStack, StackSidebar, and ActionBar to hold
buttons at the bottom and allows closing with the ESC key.

Add a base preferences dialog

---

files/usr/share/icons/hicolor/scalable/actions/media-mount-symbolic.svg

Inspired by the `media-mount-symbolic` icon from the Breeze icon theme.
Based on the `media-eject-symbolic` icon from the Adwaita icon theme.
Use case: Right-click action to mount devices in nemo

Add media-mount-symbolic icon

---

libxapp/xapp-glade-catalog.c
libxapp/xapp-glade-catalog.xml
libxapp/xapp-stack-sidebar.c
libxapp/xapp-stack-sidebar.h
pygobject/XApp.py

Since we chose the horizontal layout as the preferred style, remove the
support for vertical layouts. This simplifies things a bit. Also remove
inserting a separator between each row.

stack-sidear: Simplify a bit

---

libxapp/xapp-icon-chooser-button.c

This makes the XAppIconChooserDialog inherit the modal state from the toplevel widget of the icon chooser button. This fixes an issue where the dialog is unresponsive when the button is pressed while in a modal window - such as the dialog that opens when adding a new entry to the editable list widget in Cinnamon's xlet settings.

xapp-icon-chooser-button.c: make dialog inherit modal state

---

libxapp/xapp-icon-chooser-button.c
libxapp/xapp-icon-chooser-dialog.c
libxapp/xapp-stack-sidebar.c

Removes unused vars and an unused function with an incorrect
return type.

libxapp: cleanup compile warnings

---

docs/xapp-docs.xml
libxapp/g-codegen.py
libxapp/meson.build
libxapp/org.x.StatusIcon.xml
libxapp/xapp-status-icon-monitor.c
libxapp/xapp-status-icon-monitor.h
libxapp/xapp-status-icon.c
libxapp/xapp-status-icon.h
test-scripts/xapp-status-applet
test-scripts/xapp-status-icon

- added monitor class (we can rename or whatever if desired)
- updated test applet to utilize new class
todo:
- (mostly done) Need to fix monitor handling click events (issue with introspection I need to fix first)
- Need to evaluate if any other handling should be done in this class (some menu handling?)
- (done)the status icon class should utilize the service part of the generated interface (will simplify some code)
- (done)need to have the status icon handle switching between Gtk and XApp better.
- add debugging info, document
related: https://github.com/linuxmint/cinnamon/pull/8836

Add an applet/monitor class for status icons

---

libxapp/xapp-icon-chooser-dialog.c
libxapp/xapp-icon-chooser-dialog.h
test-scripts/xapp-icon-chooser-dialog

* Adds a default_icon property which, when set, will cause the dialog to show a revert button. When that button is pressed, it will set the currently selected item to the default icon.
* Adds a *_add_custom_category () function which allows to specify a new category in the dialog's category list, which will (when selected) show the icons from the provided list of icon names.

Add some new features to the icon chooser dialog

---

libxapp/xapp-icon-chooser-dialog.c

With the addition of the xapp_icon_chooser_dialog_add_custom_category it is now possible to have non-existent icon names. To prevent a segfault, these icon names are now skipped.

xapp-icon-chooser-dialog.c: prevent segfault on non-existent icon name

---

README.md

This one-character change fixes the API Reference link in the README.

readme: Fix API Reference URL

---

scripts/xfce4-set-wallpaper

Hi, there is an error in `xfce4-set-wallpaper` script: `xfce4-desktop` requires an absolute path to show the wallpaper, but the script doesn't do any check. So if the user run the script with a relative path, like `xfce4-set-wallpaper my-background.png` it fails to set correctly the wallpaper.
I fixed using `realpath` to obtain the absolute path, it is installed by default on Fedora 32, but I am not sure on other operating systems. Another option is to use `readlink`, but it may be not installed.

xfce4-set-wallpaper: resolve relative path

---

meson.build

We have to use datadir to effect dbus-1.pc https://github.com/freedesktop/dbus/blob/b387bd4d2916416f1376fe9feeee61e557d571de/dbus-1.pc.in#L11

build: use datadir in define_variable for dbus_services_dir

---

data/80xapp-gtk3-module.sh
data/meson.build

Xsession is something specific to e.g. GDM or lightdm, which in turn sources all shell scripts in /etc/X11/xinit/xinitrc.d
Meanwhile the standard xorg-xinit provided xinitrc also sources the scripts in /etc/X11/xinit/xinitrc.d
/etc/X11/Xsession.d works absolutely nowhere other than Debian, and Debian will eventually load the standard /etc/X11/xinit/xinitrc.d directory via sourcing .xinitrc anyway; hence moving this file to the standard location will result in this working as intended everywhere.

fix xorg-server startup variable

---

data/80xapp-gtk3-module.sh

rpm strips the executable perms if there is no shebang.
+ /usr/lib/rpm/redhat/brp-mangle-shebangs
mangling shebang in /usr/bin/xfce4-set-wallpaper from /bin/bash to #!/usr/bin/bash
*** WARNING: ./etc/X11/xinit/xinitrc.d/80xapp-gtk3-module.sh is executable but has no shebang, removing executable bit
Processing files: xapps-2.0.1-2.fc33.x86_64

Add shebang to 80xapp-gtk3-module.sh

---

data/80xapp-gtk3-module.sh

Change shebang pathm ubuntu, debian and mandriva use /bin/bash.
Fixes #123

Change shebang path

---

libxapp/meson.build
libxapp/xapp-style-manager.c
libxapp/xapp-style-manager.h

Usage
-----
c:
```
GtkWidget *widget = gtk_label_new ("blah");
XAppStyleManager *style_manager = xapp_style_manager_new ();
xapp_style_manager_set_widget (style_manager, widget);
xapp_style_manager_set_style_property (style_manager, "color", "red");
```
Python:
```
widget = Gtk.Label(label="blah")
style_manager = XApp.StyleManager(widget=widget)
style_manager.set_style_property("color", "red")
```

Add a class to programmatically set styling on a particular widget.

---

libxapp/xapp-style-manager.c
libxapp/xapp-style-manager.h
libxapp/xapp-util.c
libxapp/xapp-util.h

Also adds a convenience method to the style manager.

util: add a utility function to convert from a pango font string to css

---

libxapp/meson.build

This caused an issue where a package tag wouldn't generate. This could
cause problems with other tools, such as gtk-rs's rust binding generation
tool.
Closes #141

meson gir: Export 'xapp' as a package

---

libxapp/meson.build

The Nix package manager used by NixOS (and available on all unix systems), uses a sandboxed environment where it is not possible to have global building dependencies. Without this change the build with fails with:
```
[68/100] Compiling C object xapp-sn-watcher/xapp-sn-watcher.p/meson-generated_.._sn-item-interface.c.o
FAILED: xapp-sn-watcher/xapp-sn-watcher.p/meson-generated_.._sn-item-interface.c.o 
gcc -Ixapp-sn-watcher/xapp-sn-watcher.p -Ixapp-sn-watcher -I../xapp-sn-watcher -I. -I.. -Ilibxapp -I/nix/store/0a9b4bv93s2b94q0fa2h4r0m55qy92fx-glib-2.72.3-dev/include -I/nix/store/0a9b4bv93s2b94q0fa2h4r0m55qy92fx-glib-2.72.3-dev/include/glib-2.0 -I/nix/store/i4k2ahrb0rzr7f2ni02nljcffawvpqpg-glib-2.72.3/lib/glib-2.0/include -I/nix/store/qbvaw0nl5rvmwm6ljsmvq7ciazqvcd2j-gtk+3-3.24.34-dev/inclu …
```

libxapp: add missing gio-unix-2.0 dependency

---

libxapp/meson.build

This adds an library which is required to fix underlinking.

add missing gmodule depends

---

docs/meson.build
libxapp/meson.build
meson.build
status-applets/mate/meson.build

Similar to linuxmint/cinnamon#11870
Similar to linuxmint/cinnamon-control-center#318
Similar to linuxmint/cinnamon-desktop#234
Similar to linuxmint/cinnamon-menus#67
Similar to linuxmint/cinnamon-screensaver#444
Similar to linuxmint/cinnamon-session#155
Similar to linuxmint/cinnamon-settings-daemon#383
Similar to linuxmint/cjs#119
Similar to linuxmint/muffin#675
Similar to linuxmint/nemo#3316
Similar to linuxmint/nemo-extensions#496

Fix meson.build deprecations up to 0.56.0

---

meson_options.txt
pygobject/meson.build

Allow installing GObject Introspection overrides to multiple system python installations. This is something Gentoo supports (I'm not sure about other distros) so this has made packaging a little messy.
Switching `py-overrides-dir` to `array` allows for passing multiple paths as a comma separated string, and should maintain compatibility with existing build harnesses.
This also switches from `find_program` to `python.find_installation` and adds a `python_target` to allow specifying multiple installation targets instead of a list of paths. I defaulted `python_target` to just `python3`, as I assume `python` and `python3` refer to the same python installation on modern systems. This also matches the default for `python3-xapp`.
```
meson setup ... -Dpython_target=python3.11,python3.12 ...
``` …

Allow installing GObject Introspection overrides to multiple python installations

---

libxapp/meson.build
meson.build
meson_options.txt

Another minor packaging improvement for Gentoo, to allow introspection and vala bindings to be disabled.

Add options to disable building introspection and vala bindings.

---

libxapp/xapp-gpu-offload-helper.c
libxapp/xapp-gpu-offload-helper.h

Adds proper discrete GPU detection through switcheroo-control.
Required switcheroo-control PR https://gitlab.freedesktop.org/hadess/switcheroo-control/-/merge_requests/69
KDE Counterpart: https://invent.kde.org/frameworks/kio/-/merge_requests/1556
GNOME Counterpart: https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/3193

 Improve discrete GPU detection using switcheroo-control
